/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as ComponentsComponentRouteImport } from './routes/components/$component'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/docs/theming',
  path: '/docs/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/docs/installation',
  path: '/docs/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/docs/getting-started',
  path: '/docs/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentRoute = ComponentsComponentRouteImport.update({
  id: '/components/$component',
  path: '/components/$component',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/themes': typeof ThemesRoute
  '/components/$component': typeof ComponentsComponentRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/themes': typeof ThemesRoute
  '/components/$component': typeof ComponentsComponentRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/themes': typeof ThemesRoute
  '/components/$component': typeof ComponentsComponentRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/themes'
    | '/components/$component'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/theming'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/themes'
    | '/components/$component'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/theming'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/themes'
    | '/components/$component'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/theming'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  ThemesRoute: typeof ThemesRoute
  ComponentsComponentRoute: typeof ComponentsComponentRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsThemingRoute: typeof DocsThemingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/docs/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$component': {
      id: '/components/$component'
      path: '/components/$component'
      fullPath: '/components/$component'
      preLoaderRoute: typeof ComponentsComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  ThemesRoute: ThemesRoute,
  ComponentsComponentRoute: ComponentsComponentRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsThemingRoute: DocsThemingRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
